# Generated by Django 4.1.3 on 2022-11-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullmenu',
            options={'ordering': ['title']},
        ),
    ]
